import type { Metadata } from "next";
import "../global/globals.css";
import { Providers } from "./provider";

export const metadata: Metadata = {
  title: "APARICIO | Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}